export type Platform = 'instagram' | 'tiktok' | 'facebook';

export type SocialPost = {
  id: string;
  platform: Platform;
  url: string;
  title: string;
  summary: string;
  publishedAt?: string;
  aspectRatio: `${number} / ${number}`;
  thumbnail?: string;
  embedUrl?: string;
  embedHeight?: number;
};

// Add compressed thumbnails under public/thumbs for the lightest initial load.
// The social-submission processor adds entries here after retrieving public metadata.
export const posts: SocialPost[] = [
  {
    id: 'facebook-547c08efd5',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/27816677368007676/",
    title: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies a",
    summary: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies at the 15th @attitudemag awards as headline sponsor celebrating all things love. Rooted within our DNA, we’re",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-547c08efd5.jpg',
  },
  {
    id: 'facebook-0d7989e986',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/3510536449121973/",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-0d7989e986.jpg',
  },
  {
    id: 'facebook-6e52e135d3',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1392731379241161/",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-6e52e135d3.jpg',
  },
  {
    id: 'facebook-d518eea85c',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1123837760222643/",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-d518eea85c.jpg',
  },
  {
    id: 'facebook-c660e21af9',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1553289439901878/",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-c660e21af9.jpg',
  },
  {
    id: 'facebook-ce66ac4c05',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1323613849725784/",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-ce66ac4c05.jpg',
  },
  {
    id: 'facebook-af46c0fee6',
    platform: 'facebook',
    url: "https://www.facebook.com/virginatlantic/posts/pfbid02UNfwYDzhn3zPgYLuj8gimBD76SY2rucZYZ6J1zjvF56pSH2oF8DRGSwyUUfypVjzl",
    title: "If not now, when?",
    summary: "If not now, when? ✈️ We asked our people the moments which made their holiday. From big adventures to the little things that make a trip unforgettable, there’s always something wor",
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/facebook-af46c0fee6.jpg',
  },
  {
    id: 'facebook-327254d3e7',
    platform: 'facebook',
    url: "https://www.facebook.com/virginatlantic/posts/pfbid0MAj3abtGVv5mGTnFTQREDV2g4vAt5zA3DSNJ7XgpGrg3CVDpv3gZoD9WVafiPtDQl",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Las Vegas, London, Grenada, Seoul, New York, or Cape Town. There’s a whole world worth seeing in full colour, so where are you he",
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/facebook-327254d3e7.jpg',
  },
  {
    id: 'facebook-df856a948e',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/2267635397366061/",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_e_j and @Kad21 swapped the starting line for our Mile High Tea, with our expert James deciding who served it best. But fir",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-df856a948e.jpg',
  },
  {
    id: 'facebook-8a78c99e6b',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1046367088284769/",
    title: "Sinead (Cabin Crew)",
    summary: "Where you’re going matters. How you get there does too ✈️ LA’s on our mind, but there’s a whole lot of journey and adventure to get us there. 📸: Sinead (Cabin Crew)",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-8a78c99e6b.jpg',
  },
  {
    id: 'tiktok-bb57c45656',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694055542972615958",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-bb57c45656.jpg',
  },
  {
    id: 'tiktok-f55d4b785e',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694045839253196054",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-f55d4b785e.jpg',
  },
  {
    id: 'tiktok-b559a26eb7',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694034810192301335",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the Virgin Atlantic @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-b559a26eb7.jpg',
  },
  {
    id: 'tiktok-ff0dd6b4f9',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7691264681054424342",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    publishedAt: '2026-09-30',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-ff0dd6b4f9.jpg',
  },
  {
    id: 'tiktok-707471191d',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7689491418330434839",
    title: "awb.photo #virginatlantic #economy",
    summary: "Replying to @Sandra Farn - We’re DELIGHTed to hear you think this isn’t economy ✈️ 📸: awb.photo #virginatlantic #economy",
    publishedAt: '2026-09-25',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-707471191d.jpg',
  },
  {
    id: 'tiktok-b8077ce0f2',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7689145373692005654",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️",
    publishedAt: '2026-09-24',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-b8077ce0f2.jpg',
  },
  {
    id: 'tiktok-78e9c62883',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7687662528637324577",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Cape Town, Las Vegas, New York, Grenada, Seoul or London. There’s a whole world worth seeing in full colour, so where are you hea",
    publishedAt: '2026-09-20',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-78e9c62883.jpg',
  },
  {
    id: 'tiktok-da52342633',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7684326399091477782",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_jarman and @kadcoxofficial swapped the starting line for our Mile High Tea, with our experts deciding who served it best. ",
    publishedAt: '2026-09-11',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-da52342633.jpg',
  },
  {
    id: 'tiktok-ee3fa31fc4',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7681727555614838039",
    title: "Los Angeles, we’re bringing the team 🇬🇧 We’re officially joining @Team",
    summary: "Los Angeles, we’re bringing the team 🇬🇧 We’re officially joining @TeamGB and @ParalympicsGB as Official Airline Partner for the Los Angeles 2028 Olympic and Paralympic Games. @Ja",
    publishedAt: '2026-09-04',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-ee3fa31fc4.jpg',
  },
  {
    id: 'tiktok-600c422b5e',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7681006188640652566",
    title: "@ChloeFids",
    summary: "Turns out, we’ve got a thing for LA 🇺🇸 Something tells us we’ll be back. 📸 : @ChloeFids",
    publishedAt: '2026-09-02',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-600c422b5e.jpg',
  },
  {
    id: 'instagram-00829b143c',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeO45ifOGgu/?hl=en",
    title: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies a",
    summary: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies at the 15th @attitudemag awards as headline sponsor celebrating all things love. Rooted within our DNA, we’re",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-00829b143c.jpg',
  },
  {
    id: 'instagram-b5420ad622',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNazuLusws/?hl=en",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.\".",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-b5420ad622.jpg',
  },
  {
    id: 'instagram-556109666d',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNVcchO8sZ/?hl=en",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.\".",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-556109666d.jpg',
  },
  {
    id: 'instagram-606477a084',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNQkpsOc0A/?hl=en",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.\".",
    publishedAt: '2026-02-13',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-606477a084.jpg',
  },
  {
    id: 'instagram-0c439029b6',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeKN_0aB7iR/?hl=en",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️\".",
    publishedAt: '2026-02-12',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-0c439029b6.jpg',
  },
  {
    id: 'instagram-9fb308ee13',
    platform: 'instagram',
    url: "https://www.instagram.com/p/Dd6CFc_OpGE/?hl=en",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    publishedAt: '2026-02-06',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-9fb308ee13.jpg',
  },
  {
    id: 'instagram-f32acb390c',
    platform: 'instagram',
    url: "https://www.instagram.com/p/Dd4J8FCjnBu/?hl=en&img_index=1",
    title: "If not now, when?",
    summary: "If not now, when? ✈️ We asked our people the moments which made their holiday. From big adventures to the little things that make a trip unforgettable, there’s always something wor",
    publishedAt: '2026-02-05',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-f32acb390c.jpg',
  },
  {
    id: 'instagram-a3894b4881',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdwaFPODCd_/?hl=en",
    title: "POV: You’re the lucky Sailor helping us celebrate 2 million (and countin",
    summary: "POV: You’re the lucky Sailor helping us celebrate 2 million (and counting!). Which one are you bragging about first? 👇 🎉 Mega RockStar upgrade 🎉 Beachfront cabana in Bimini 🎉 T",
    publishedAt: '2026-02-02',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-a3894b4881.jpg',
  },
  {
    id: 'instagram-7f06dc6b4d',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdhELMkjk3z/?hl=en&img_index=1",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Las Vegas, London, Grenada, Seoul, New York, or Cape Town. There’s a whole world worth seeing in full colour, so where are you he",
    publishedAt: '2026-01-27',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-7f06dc6b4d.jpg',
  },
  {
    id: 'instagram-7778bb020a',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdJ6zfVuAO2/?hl=en",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_e_j and @Kad21 swapped the starting line for our Mile High Tea, with our expert James deciding who served it best. #TeamGB",
    publishedAt: '2026-01-18',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-7778bb020a.jpg',
  },
];
