export type Platform = 'instagram' | 'tiktok' | 'facebook';

export type SocialPost = {
  id: string;
  platform: Platform;
  url: string;
  title: string;
  summary: string;
  publishedAt?: string;
  aspectRatio: `${number} / ${number}`;
  thumbnail?: string;
  embedUrl?: string;
  embedHeight?: number;
};

// Add compressed thumbnails under public/thumbs for the lightest initial load.
// The social-submission processor adds entries here after retrieving public metadata.
export const posts: SocialPost[] = [
  {
    id: 'facebook-547c08efd5',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/27816677368007676/",
    title: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies a",
    summary: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies at the 15th @attitudemag awards as headline sponsor celebrating all things love. Rooted within our DNA, we’re",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-547c08efd5.jpg',
  },
  {
    id: 'facebook-0d7989e986',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/3510536449121973/",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-0d7989e986.jpg',
  },
  {
    id: 'facebook-6e52e135d3',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1392731379241161/",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-6e52e135d3.jpg',
  },
  {
    id: 'facebook-d518eea85c',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1123837760222643/",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-d518eea85c.jpg',
  },
  {
    id: 'facebook-c660e21af9',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1553289439901878/",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-c660e21af9.jpg',
  },
  {
    id: 'facebook-ce66ac4c05',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1323613849725784/",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-ce66ac4c05.jpg',
  },
  {
    id: 'facebook-af46c0fee6',
    platform: 'facebook',
    url: "https://www.facebook.com/virginatlantic/posts/pfbid02UNfwYDzhn3zPgYLuj8gimBD76SY2rucZYZ6J1zjvF56pSH2oF8DRGSwyUUfypVjzl",
    title: "If not now, when?",
    summary: "If not now, when? ✈️ We asked our people the moments which made their holiday. From big adventures to the little things that make a trip unforgettable, there’s always something wor",
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/facebook-af46c0fee6.jpg',
  },
  {
    id: 'facebook-327254d3e7',
    platform: 'facebook',
    url: "https://www.facebook.com/virginatlantic/posts/pfbid0MAj3abtGVv5mGTnFTQREDV2g4vAt5zA3DSNJ7XgpGrg3CVDpv3gZoD9WVafiPtDQl",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Las Vegas, London, Grenada, Seoul, New York, or Cape Town. There’s a whole world worth seeing in full colour, so where are you he",
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/facebook-327254d3e7.jpg',
  },
  {
    id: 'facebook-df856a948e',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/2267635397366061/",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_e_j and @Kad21 swapped the starting line for our Mile High Tea, with our expert James deciding who served it best. But fir",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-df856a948e.jpg',
  },
  {
    id: 'facebook-8a78c99e6b',
    platform: 'facebook',
    url: "https://www.facebook.com/reel/1046367088284769/",
    title: "Sinead (Cabin Crew)",
    summary: "Where you’re going matters. How you get there does too ✈️ LA’s on our mind, but there’s a whole lot of journey and adventure to get us there. 📸: Sinead (Cabin Crew)",
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/facebook-8a78c99e6b.jpg',
  },
  {
    id: 'tiktok-bb57c45656',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694055542972615958",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-bb57c45656.jpg',
  },
  {
    id: 'tiktok-f55d4b785e',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694045839253196054",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-f55d4b785e.jpg',
  },
  {
    id: 'tiktok-b559a26eb7',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7694034810192301335",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the Virgin Atlantic @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.",
    publishedAt: '2026-10-07',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-b559a26eb7.jpg',
  },
  {
    id: 'tiktok-ff0dd6b4f9',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7691264681054424342",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    publishedAt: '2026-09-30',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-ff0dd6b4f9.jpg',
  },
  {
    id: 'tiktok-707471191d',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7689491418330434839",
    title: "awb.photo #virginatlantic #economy",
    summary: "Replying to @Sandra Farn - We’re DELIGHTed to hear you think this isn’t economy ✈️ 📸: awb.photo #virginatlantic #economy",
    publishedAt: '2026-09-25',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-707471191d.jpg',
  },
  {
    id: 'tiktok-b8077ce0f2',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7689145373692005654",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️",
    publishedAt: '2026-09-24',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-b8077ce0f2.jpg',
  },
  {
    id: 'tiktok-78e9c62883',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7687662528637324577",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Cape Town, Las Vegas, New York, Grenada, Seoul or London. There’s a whole world worth seeing in full colour, so where are you hea",
    publishedAt: '2026-09-20',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-78e9c62883.jpg',
  },
  {
    id: 'tiktok-da52342633',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7684326399091477782",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_jarman and @kadcoxofficial swapped the starting line for our Mile High Tea, with our experts deciding who served it best. ",
    publishedAt: '2026-09-11',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-da52342633.jpg',
  },
  {
    id: 'tiktok-ee3fa31fc4',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7681727555614838039",
    title: "Los Angeles, we’re bringing the team 🇬🇧 We’re officially joining @Team",
    summary: "Los Angeles, we’re bringing the team 🇬🇧 We’re officially joining @TeamGB and @ParalympicsGB as Official Airline Partner for the Los Angeles 2028 Olympic and Paralympic Games. @Ja",
    publishedAt: '2026-09-04',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-ee3fa31fc4.jpg',
  },
  {
    id: 'tiktok-600c422b5e',
    platform: 'tiktok',
    url: "https://www.tiktok.com/@virginatlantic/video/7681006188640652566",
    title: "@ChloeFids",
    summary: "Turns out, we’ve got a thing for LA 🇺🇸 Something tells us we’ll be back. 📸 : @ChloeFids",
    publishedAt: '2026-09-02',
    aspectRatio: '9 / 16',
    thumbnail: '/thumbs/tiktok-600c422b5e.jpg',
  },
  {
    id: 'instagram-00829b143c',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeO45ifOGgu/?hl=en",
    title: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies a",
    summary: "Serving attitude 👠 Last night we joined our LGBTQ+ friends and allies at the 15th @attitudemag awards as headline sponsor celebrating all things love. Rooted within our DNA, we’re",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-00829b143c.jpg',
  },
  {
    id: 'instagram-b5420ad622',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNazuLusws/?hl=en",
    title: "No itinerary?",
    summary: "No itinerary? No regrets ✈️ The @attitudemag Awards red carpet weighs in on the holiday choices that make the best stories.\".",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-b5420ad622.jpg',
  },
  {
    id: 'instagram-556109666d',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNVcchO8sZ/?hl=en",
    title: "Home you would never.",
    summary: "Home you would never. Holiday you, however… 👀 We took the important questions to the @attitudemag Awards red carpet. Safe to say, inhibitions were checked at departure.\".",
    publishedAt: '2026-02-14',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-556109666d.jpg',
  },
  {
    id: 'instagram-606477a084',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeNQkpsOc0A/?hl=en",
    title: "Attitude?",
    summary: "Attitude? My bag ❤️ Catching up with stars at the @attitudemag Awards. Turns out what happens on holiday… makes excellent red carpet conversation.\".",
    publishedAt: '2026-02-13',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-606477a084.jpg',
  },
  {
    id: 'instagram-0c439029b6',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DeKN_0aB7iR/?hl=en",
    title: "Our Mile High Tea has fans in high places ✈️",
    summary: "Our Mile High Tea has fans in high places ✈️\".",
    publishedAt: '2026-02-12',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-0c439029b6.jpg',
  },
  {
    id: 'instagram-9fb308ee13',
    platform: 'instagram',
    url: "https://www.instagram.com/p/Dd6CFc_OpGE/?hl=en",
    title: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a",
    summary: "Viva Forever ✨ G-VLJB, pays tribute to Lady Joan Branson, who was such a special part of the Virgin Atlantic story from the very beginning, joining our first flight in 1984 and lea",
    publishedAt: '2026-02-06',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-9fb308ee13.jpg',
  },
  {
    id: 'instagram-f32acb390c',
    platform: 'instagram',
    url: "https://www.instagram.com/p/Dd4J8FCjnBu/?hl=en&img_index=1",
    title: "If not now, when?",
    summary: "If not now, when? ✈️ We asked our people the moments which made their holiday. From big adventures to the little things that make a trip unforgettable, there’s always something wor",
    publishedAt: '2026-02-05',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-f32acb390c.jpg',
  },
  {
    id: 'instagram-a3894b4881',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdwaFPODCd_/?hl=en",
    title: "POV: You’re the lucky Sailor helping us celebrate 2 million (and countin",
    summary: "POV: You’re the lucky Sailor helping us celebrate 2 million (and counting!). Which one are you bragging about first? 👇 🎉 Mega RockStar upgrade 🎉 Beachfront cabana in Bimini 🎉 T",
    publishedAt: '2026-02-02',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-a3894b4881.jpg',
  },
  {
    id: 'instagram-7f06dc6b4d',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdhELMkjk3z/?hl=en&img_index=1",
    title: "You pick the colour.",
    summary: "You pick the colour. We’ll pick the destination 🎨 Las Vegas, London, Grenada, Seoul, New York, or Cape Town. There’s a whole world worth seeing in full colour, so where are you he",
    publishedAt: '2026-01-27',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-7f06dc6b4d.jpg',
  },
  {
    id: 'instagram-7778bb020a',
    platform: 'instagram',
    url: "https://www.instagram.com/p/DdJ6zfVuAO2/?hl=en",
    title: "World-class athletes.",
    summary: "World-class athletes. Upper class scone opinions 👀 @Jake_e_j and @Kad21 swapped the starting line for our Mile High Tea, with our expert James deciding who served it best. #TeamGB",
    publishedAt: '2026-01-18',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-7778bb020a.jpg',
  },
  {
    id: 'instagram-89d63e9518',
    platform: 'instagram',
    url: "https://www.instagram.com/millypickles/reel/DdCIkfiNgk7/",
    title: "The news is officially out 👀 Check in for LA 2028 is now open 🤪 and @v",
    summary: "❤️ @virginatlantic X @VirginStartUp Innovation Challenge ~ launching in early 2027, giving you the chance to help solve real challenges from accessibility to wellness and performan",
    publishedAt: '2026-01-15',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-89d63e9518.jpg',
  },
  {
    id: 'instagram-aac62530b9',
    platform: 'instagram',
    url: "https://www.instagram.com/austyn_farrell/reel/DdCCRPIt87u/",
    title: "Celebrating 600 days sober… WHATT 🤯 I know it may sound cringe to some ",
    summary: "Celebrating 600 days sober… WHATT 🤯 I know it may sound cringe to some of you, but for me, choosing the sober life has genuinely given me a second chance at life. In all honesty, ",
    publishedAt: '2026-01-15',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-aac62530b9.jpg',
  },
  {
    id: 'instagram-a8b1669ad2',
    platform: 'instagram',
    url: "https://www.instagram.com/florrietyler/reel/Dc_pOAFMs7B/",
    title: "and it’s the perfect day for @virginatlantic celebrating their new partn",
    summary: "and it’s the perfect day for @virginatlantic celebrating their new partnership with Team GB and ParalympicsGB for #LA2028 ! 🙌🏼 #perfectday AD\".",
    publishedAt: '2026-01-14',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-a8b1669ad2.jpg',
  },
  {
    id: 'instagram-fac6a7ddb4',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/Dc6ePwiuze6/",
    title: "Where you’re going matters.",
    summary: "Sinead (Cabin Crew)\".",
    publishedAt: '2026-01-12',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-fac6a7ddb4.jpg',
  },
  {
    id: 'instagram-bedbf0c068',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/Dc1RmAgoZOs/",
    title: "Not your usual baggage 👀 But we know exactly where it’s going.",
    summary: "Not your usual baggage 👀 But we know exactly where it’s going. Some things are just too important to leave behind.\".",
    publishedAt: '2026-01-10',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-bedbf0c068.jpg',
  },
  {
    id: 'instagram-07e8d54db1',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/Dcyy4vgODv1/",
    title: "Turns out, we’ve got a thing for LA 🇺🇸 Something tells us we’ll be bac",
    summary: "Turns out, we’ve got a thing for LA 🇺🇸 Something tells us we’ll be back. 📸 : @chloefids\".",
    publishedAt: '2026-01-09',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-07e8d54db1.jpg',
  },
  {
    id: 'instagram-096d7fe36b',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/DcjCoWFMGXG/",
    title: "It’s never too late for a new departure ✈️ Three years after we first sh",
    summary: "It’s never too late for a new departure ✈️ Three years after we first shared Tim’s story, he’s still proving that a career change can take you somewhere unexpected. From starting a",
    publishedAt: '2026-01-03',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-096d7fe36b.jpg',
  },
  {
    id: 'instagram-ccec514dde',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/DcROOy4jgv-/",
    title: "We’ve got chills, they’re multiplying… ☀️ And 1 million Virgin Points mi",
    summary: "We’ve got chills, they’re multiplying… ☀️ And 1 million Virgin Points might have something to do with it. If you’re heading to @secret_cinema Grease: The Immersive Movie Musical, f",
    publishedAt: '2025-12-27',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-ccec514dde.jpg',
  },
  {
    id: 'instagram-241a753ec0',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/DcLgVSYjlnm/",
    title: "If not now, when?",
    summary: "If not now, when? ✈️ We asked our crew, now we’re asking you. What’s the thing you’ve always wanted to say yes to on holiday? The place you’ve been meaning to go, the experience yo",
    publishedAt: '2025-12-25',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-241a753ec0.jpg',
  },
  {
    id: 'instagram-9e5affad73',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/Db3iNLJk5zh/",
    title: "Raise a glass to Champagne Supernova 🥂 Paying tribute to 30 years of ca",
    summary: "Raise a glass to Champagne Supernova 🥂 Paying tribute to 30 years of calling Manchester our home in the North, G-VMAN celebrates the city, its spirit and the journeys we've shared",
    publishedAt: '2025-12-17',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-9e5affad73.jpg',
  },
  {
    id: 'instagram-a2afdd8c60',
    platform: 'instagram',
    url: "https://www.instagram.com/virgin/p/Dbqn9KeCOEs/",
    title: "A cancelled flight.",
    summary: "A cancelled flight. Stranded passengers. A handwritten sign offering seats for $39. That small idea became @virginatlantic ✈️\".",
    publishedAt: '2025-12-12',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-a2afdd8c60.jpg',
  },
  {
    id: 'instagram-8d641f47c1',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/DbiwPUfjIfX/",
    title: "Hear our Pride ✨ Celebrating all things love this weekend @brightonpride",
    summary: "Hear our Pride ✨ Celebrating all things love this weekend @brightonprideofficial together with our friends @delta. We’ve been a supporter of the LGBTQIA+ community since the beginn",
    publishedAt: '2025-12-09',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-8d641f47c1.jpg',
  },
  {
    id: 'instagram-86d015c6af',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/DbGn8Zvu7Gi/",
    title: "Skip the traffic.",
    summary: "Skip the traffic. Take the sky 🚁 The way we travel is changing. Together with @jobyaviation, we’re taking the next step towards bringing electric air taxi services to the UK, help",
    publishedAt: '2025-11-28',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-86d015c6af.jpg',
  },
  {
    id: 'instagram-8e755e0099',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/Da8ImciAIUv/",
    title: "Wishing the happiest of birthdays to our founder, Sir @richardbranson 🎂",
    summary: "Wishing the happiest of birthdays to our founder, Sir @richardbranson 🎂 Another year around the sun, and still taking on the sea, skies and stars. Our A330neo Ruby Rebel, G-VSRB h",
    publishedAt: '2025-11-24',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-8e755e0099.jpg',
  },
  {
    id: 'instagram-7c2156454d',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/Da0ncS4uJIj/",
    title: "Cleared for kick-off ⚽ Our Heathrow team gained a few new team mates wit",
    summary: "Cleared for kick-off ⚽ Our Heathrow team gained a few new team mates with expert luggage handling and slick footwork for celebration worthy checkin. Atlanta’s calling, whether you’",
    publishedAt: '2025-11-21',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-7c2156454d.jpg',
  },
  {
    id: 'instagram-aba5bde536',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/reel/DayAKPZODIw/",
    title: "Here’s your sign to say yes 🌏 To the trip.",
    summary: "Here’s your sign to say yes 🌏 To the trip. To dinner that turns into hours. To seeing @santandave and @stormzy at 70. And to the people who make every journey unforgettable.\".",
    publishedAt: '2025-11-20',
    aspectRatio: '4 / 5',
    thumbnail: '/thumbs/instagram-aba5bde536.jpg',
  },
  {
    id: 'instagram-3ae853cdd0',
    platform: 'instagram',
    url: "https://www.instagram.com/jobyaviation/p/DavMERHlgum/",
    title: "London, thank you for the warm welcome and your excitement for quiet, el",
    summary: "London, thank you for the warm welcome and your excitement for quiet, electric flight. Three days beside Tower Bridge, thousands of visitors, and one full-scale model of our electr",
    publishedAt: '2025-11-19',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-3ae853cdd0.jpg',
  },
  {
    id: 'instagram-cb82d77df2',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/DarvE1uOPL3/",
    title: "The journey continues.",
    summary: "The journey continues. ✈️ One step closer. Looks like it’s not just football that isn’t coming home yet. Wilbur and Orville are enjoying the ride a little longer. After all, a pinc",
    publishedAt: '2025-11-18',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-cb82d77df2.jpg',
  },
  {
    id: 'instagram-1ea776eb0f',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/Dapyp6eDp76/",
    title: "A start worthy flight deck line-up ✈️ Whether you’re touching down in th",
    summary: "A start worthy flight deck line-up ✈️ Whether you’re touching down in the Miami heat or cheering from home, here’s to the journeys that bring us together. Come on, England\".",
    publishedAt: '2025-11-17',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-1ea776eb0f.jpg',
  },
  {
    id: 'instagram-2ab7c6fe32',
    platform: 'instagram',
    url: "https://www.instagram.com/virginatlantic/p/Dan5HhYjhqE/",
    title: "Seoul, served in Shoreditch 🇰🇷 Heart + Seoul has arrived, bringing the",
    summary: "Seoul, served in Shoreditch 🇰🇷 Heart + Seoul has arrived, bringing the flavours, traditions and stories behind one of the world’s most exciting cities to London for two days only",
    publishedAt: '2025-11-16',
    aspectRatio: '1 / 1',
    thumbnail: '/thumbs/instagram-2ab7c6fe32.jpg',
  },
];
